MovieMatrix/Models/Actor.cs

using System.Collections.Generic;

namespace MovieMatrix.Models {
    
    public class Actor {
        public bool adult { get; set; }
        public List<string> also_known_as { get; set; }
        public string biography { get; set; }
        public string birthday { get; set; }
        public object deathday { get; set; }
        public int gender { get; set; }
        public object homepage { get; set; }
        public int id { get; set; }
        public string imdb_id { get; set; }
        public string known_for_department { get; set; }
        public string name { get; set; }
        public string place_of_birth { get; set; }
        public double popularity { get; set; }
        public string profile_path { get; set; }

        public int GetAge() {
            int age = 0;
            return age;
        }
    }
}

MovieMatrix/Pages/Actor.cshtml.cs

using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieMatrix.Models;


namespace MovieMatrix.Pages {
    public class ActorModel : PageModel { 

      //  public string name;
        //castBio
        public string castName;
        public string castIDs;
        public string castPics;
        public string castBio;
        public string castDOB;
        public string castOrigin;
        public string castImg;
     //  public List<string> castImg = new List<string>();
        
        //
        public string movieTitle;
        public string tagline;
        public string homepage;
        public string moviePoster;

       


        public async Task OnGet(string id) {

            await Program.fetch.GetActorDetails(id);
        
                castName = Program.actor.name;
                castIDs = Program.actor.id.ToString();
                castPics = Program.actor.profile_path;
                castBio = Program.actor.biography;
                castDOB = Program.actor.birthday;
                castOrigin = Program.actor.place_of_birth;
            
        }


        public async Task GetActorImages(string id) {
            await Program.fetch.GetCast(id);
        //    foreach(Cast cast in Program.credits.cast){

            //foreach(Poster p in Program.posterSet.results)
             foreach(Profile profile in Program.profileSet.profiles){
              //  castNames.Add(cast.name);
               // castIDs.Add(cast.id.ToString());
                castImg = Program.profile.file_path;
            }
        }
            

        
    } // class
} // namespace


MovieMatrix/Pages/Index.cshtml.cs

using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieMatrix.Models;

namespace MovieMatrix.Pages {

    public class IndexModel : PageModel {        
        
        // Search:
        public List<string> posterURLs = new List<string>();
        public List<string> overviews = new List<string>();
        public List<string> movieIDs = new List<string>();
        
        public int UPCOMING_MAX_RESULTS = 0;
        public int MAX_RESULTS = 0;

        // Movie Details:
        public string movieTitle = "";
        public string tagline = "";
        public string homepage = "";
        public int budget;
        public long revenue;
        public string backdropPath = "";
        public string fullsizedPoster = "";
        public string releaseDate = "";
        public string overview = "";

        // Cast:
        public List<string> castNames = new List<string>();
        public List<string> castIDs = new List<string>();
        public List<string> castPics = new List<string>();

        public List<string> externalID = new List<string>();


        // Videos:
        public List<string> videoIDs = new List<string>();
        public int MAX_VIDEO_COUNT = 0;

        public async Task OnGet() {
            await Program.fetch.Upcoming();
            foreach(Poster upcoming in Program.upcomingSet.results) {
                posterURLs.Add(upcoming.poster_path);
                overviews.Add(upcoming.overview);
                movieIDs.Add(upcoming.id.ToString());
        
            }
            if(Program.upcomingSet.results.Count >= 10)
                UPCOMING_MAX_RESULTS = 10;
            else
                UPCOMING_MAX_RESULTS = Program.upcomingSet.results.Count;
        } // OnGet()

        public async Task OnPostSearch(string search) {
            await Program.fetch.Search(search);
            foreach(Poster p in Program.posterSet.results) {
                posterURLs.Add(p.poster_path);
                overviews.Add(p.overview);
                movieIDs.Add(p.id.ToString());
             
            }
            if(Program.posterSet.results.Count >= 10)
                MAX_RESULTS = 10;
            else
                MAX_RESULTS = Program.posterSet.results.Count;
        } // OnPostSearch()

        public async Task OnPostGetDetails(string movieID) {
            await Program.fetch.GetDetails(movieID);
            movieTitle = Program.movie.title;
            tagline = Program.movie.tagline;
            homepage = Program.movie.homepage;
            budget = Program.movie.budget;
            revenue = Program.movie.revenue;
            backdropPath = Program.movie.backdrop_path;
            fullsizedPoster = Program.movie.poster_path;
            releaseDate = Program.movie.release_date.Substring(0, 4);
            overview = Program.movie.overview;
            await GetCast(movieID);
            await GetVideos(movieID);
        } // OnPostGetDetails()

        public async Task GetCast(string movieID) {
            await Program.fetch.GetCast(movieID);
            foreach(Cast cast in Program.credits.cast){
                castNames.Add(cast.name);
                castIDs.Add(cast.id.ToString());
                castPics.Add(cast.profile_path);
                
              
            }
        } // GetCast()

        public async Task GetVideos(string movieID) {
            await Program.fetch.GetVideos(movieID);
            foreach (Video video in Program.videoSet.results) {
                videoIDs.Add(video.key);
            }
            if(videoIDs.Count >= 1)
                MAX_VIDEO_COUNT = 1;
            else
                MAX_VIDEO_COUNT = Program.posterSet.results.Count;
        } // GetCast()



        public void OnPostGetActorDetails(string castID) {
            Response.Redirect("./Actor?id=" + castID);
        } // OnPostGetActorDetails()

            
 
        
    } // class
} // namespace



  

MovieMatrix/Pages/Actor.cshtml

@page
@model ActorModel

@{
    string Actor_pic = "https://image.tmdb.org/t/p/w500" + @Model.castPics;
 
}

<div id="ActorImg">
<div id="ActorImage" style="background: url(@Actor_pic); 
        background-size: contain; background-repeat: no-repeat;"></div>

        <div id="ActorInfoBackground"></div>
             <div id="ActorInfo">
                         <h1 id="HeaderActorname" >@Model.castName</h1>
                         
                         <h3>From: @Model.castOrigin</h3>
                         <h3>Born on: @Model.castDOB</h3>
                         <br>
                         <div id="actorbio" ><h4 id="HeaderActorBio">@Model.castBio</h4></div>
                         <br>
                         <div id="actorimage" >@Model.castImg</div>
        </div>
  </div>      

  
                   
       

 


MovieMatrix/Pages/Index.cshtml

@page
@model IndexModel

@{
    string path = "https://image.tmdb.org/t/p/w500";
    string backdrop_path = "https://image.tmdb.org/t/p/w1920_and_h800_multi_faces" +
        Model.backdropPath;
}


<div id="wrapper">
<div id="search">
    <form method="POST" asp-page-handler="Search">
        <input id="searchBox" type="text" name="search" placeholder="Movie search...">
    </form>



<div id="upcoming">
    <form method="POST" asp-page-handler="GetDetails">
        @for(int i = 0; i < Model.UPCOMING_MAX_RESULTS; i++) {
            string posterPath = "";
            if(Model.posterURLs[i] != null) {
                posterPath = path + Model.posterURLs[i];
                <div class="upcomingThumb" style="background: url(@posterPath); 
                    background-size: 100%;" title="@Model.overviews[i]">
                    <input type="submit" class="upcomingThumbButton" name="movieID" 
                        value="@Model.movieIDs[i]" />
                </div>
            }
            else {
                // do nothing incomplete data!
            }
        }
    </form>
</div>
</div>

</div>

<div id="posters">
    <form method="POST" asp-page-handler="GetDetails">
        @for(int i = 0; i < Model.MAX_RESULTS; i++) {
            string posterPath = "";
            if(Model.posterURLs[i] != null) {
                posterPath = path + Model.posterURLs[i];
                <div class="thumb" style="background: url(@posterPath); 
                    background-size: 100%;" title="@Model.overviews[i]">
                    <input type="submit" class="thumbButton" name="movieID" 
                        value="@Model.movieIDs[i]" />
                </div>
            }
            else {
                // do nothing incomplete data!
            }
        }
    </form>
</div>

<!--### movie details ###-->

@if(Model.backdropPath != "") {
    <div id="details" style="background: url(@backdrop_path); 
        background-size: contain; background-repeat: no-repeat;">
        
        <div id="detailsCover">
            <div id="leftDetails">
                @{
                    string lastPosterPath = "https://image.tmdb.org/t/p/w500" +
                        Model.fullsizedPoster;
                }
                <div class="fullsizedPoster" style="background: url(@lastPosterPath); 
                    background-size: 100%;">
                </div>
                <div id="videos">
                    @for (int i = 0; i < Model.MAX_VIDEO_COUNT; i++) {
                        string youtubePath = "https://www.youtube.com/embed/" + @Model.videoIDs[i];
                        <iframe class="trailer" 
                            src="@youtubePath" 
                            title="YouTube video player" 
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" 
                            allowfullscreen>
                        </iframe>
                    }
                </div>
            </div>
            <div id="rightDetails">
                <h1>@Model.movieTitle (@Model.releaseDate)</h1>
                <h2>@Model.tagline</h2>
                <p>@Model.overview</p>
                <p class="heroText">Budget: @string.Format("{0:C}", Model.budget)</p>
                <p class="heroText">Earnings: @string.Format("{0:C}", Model.revenue)</p>
                <p>Vist the offical @Model.movieTitle homepage: 
                    <a id="homepage" href="@Model.homepage" title="Visit Movie Homepage" target="_blank">
                        here
                    </a>
                </p>
                <!-- Cast Pictures/Slider -->
                <div id="castSlider">
                    <form method="POST" asp-page-handler="GetActorDetails">
                        @for(int i = 0; i < Model.castNames.Count; i++) {
                            string castPic = "";
                            castPic = path + Model.castPics[i];
                            <div class="castCard">
                                <div class="castImage" style="background: url(@castPic); 
                                    background-size: 100%;">
                                    <input type="submit" class="castButton" name="castID" 
                                        value="@Model.castIDs[i]" />
                                </div>
                                <div class="castName">
                                    <p>@Model.castNames[i]</p>
                                </div>
                            </div>
                        }
                    </form>
                </div>
            </div>
        </div>
    </div>
    
}